ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

UPDATE users SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;

ALTER TABLE temp_registrations DROP COLUMN IF EXISTS attempts;
ALTER TABLE temp_registrations DROP COLUMN IF EXISTS password_hash;
ALTER TABLE temp_registrations ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL DEFAULT '';
UPDATE temp_registrations SET password = '' WHERE password IS NULL;
ALTER TABLE temp_registrations ALTER COLUMN password SET NOT NULL;